-- MySQL Script generated by MySQL Workbench
-- Wed Jul 22 15:08:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema iteandes_novatik
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema iteandes_novatik
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iteandes_novatik` DEFAULT CHARACTER SET utf8 ;
USE `iteandes_novatik` ;

-- -----------------------------------------------------
-- Table `iteandes_novatik`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iteandes_novatik`.`Person` (
  `idPerson` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `documentPerson` INT NOT NULL,
  `namePerson` VARCHAR(150) NOT NULL,
  `lastNamePerson` VARCHAR(150) NOT NULL,
  `dateBornPerson` DATE NOT NULL,
  `rhPerson` ENUM('A+', 'A-', 'B-', 'B+', 'O+', 'O-', 'AB-', 'AB+') NOT NULL,
  `emailPerson` VARCHAR(90) NOT NULL,
  `phonePerson` INT NOT NULL,
  `adressPerson` VARCHAR(260) NOT NULL,
  `generePerson` ENUM('Femenino', 'Masculino', 'Otro') NOT NULL,
  `userPerson` VARCHAR(45) NOT NULL,
  `passwordPerson` VARCHAR(45) NOT NULL,
  `typePerson` ENUM('Administrador', 'Secretaria', 'Docente', 'Estudiante') NOT NULL,
  `statePerson` ENUM('Activo', 'Inactivo') NOT NULL,
  `photoPerson` VARCHAR(350) NULL,
  PRIMARY KEY (`idPerson`),
  UNIQUE INDEX `documentPerson_UNIQUE` (`documentPerson` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iteandes_novatik`.`Experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iteandes_novatik`.`Experience` (
  `idExperience` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `institutionExperience` VARCHAR(300) NOT NULL,
  `dedicationExperience` VARCHAR(500) NOT NULL,
  `startExperience` DATE NOT NULL,
  `endExperince` DATE NOT NULL,
  `stateExperience` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`idExperience`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iteandes_novatik`.`TeacherStudies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iteandes_novatik`.`TeacherStudies` (
  `idTeacherStudies` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titleTeacherStudies` VARCHAR(300) NOT NULL,
  `yearStudyTeacher` SMALLINT(4) NOT NULL,
  `stateTeacherStudies` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`idTeacherStudies`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iteandes_novatik`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iteandes_novatik`.`Teacher` (
  `idTeacher` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Experience_idExperience` BIGINT UNSIGNED NOT NULL,
  `TeacherStudies_idTeacherStudies` BIGINT UNSIGNED NOT NULL,
  `Person_idPerson` BIGINT UNSIGNED NOT NULL,
  `stateTeacher` ENUM('Activo','Inactivo') NOT NULL,
  PRIMARY KEY (`idTeacher`),
  INDEX `fk_Teacher_Experience_idx` (`Experience_idExperience` ASC) ,
  INDEX `fk_Teacher_TeacherStudies1_idx` (`TeacherStudies_idTeacherStudies` ASC) ,
  INDEX `fk_Teacher_Person1_idx` (`Person_idPerson` ASC) ,
  CONSTRAINT `fk_Teacher_Experience`
    FOREIGN KEY (`Experience_idExperience`)
    REFERENCES `iteandes_novatik`.`Experience` (`idExperience`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teacher_TeacherStudies1`
    FOREIGN KEY (`TeacherStudies_idTeacherStudies`)
    REFERENCES `iteandes_novatik`.`TeacherStudies` (`idTeacherStudies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teacher_Person1`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `iteandes_novatik`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iteandes_novatik`.`Lenguages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iteandes_novatik`.`Lenguages` (
  `idLenguages` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nameLenguages` VARCHAR(40) NOT NULL,
  `stateLenguague` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`idLenguages`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iteandes_novatik`.`TeacherLenguages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iteandes_novatik`.`TeacherLenguages` (
  `idTeacherLenguages` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Teacher_idTeacher` BIGINT UNSIGNED NOT NULL,
  `Lenguages_idLenguages` BIGINT UNSIGNED NOT NULL,
  `stateTeacherLenguages` ENUM('Activo','Inactivo') NOT NULL,
  PRIMARY KEY (`idTeacherLenguages`),
  INDEX `fk_TeacherLenguages_Teacher1_idx` (`Teacher_idTeacher` ASC) ,
  INDEX `fk_TeacherLenguages_Lenguages1_idx` (`Lenguages_idLenguages` ASC) ,
  CONSTRAINT `fk_TeacherLenguages_Teacher1`
    FOREIGN KEY (`Teacher_idTeacher`)
    REFERENCES `iteandes_novatik`.`Teacher` (`idTeacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TeacherLenguages_Lenguages1`
    FOREIGN KEY (`Lenguages_idLenguages`)
    REFERENCES `iteandes_novatik`.`Lenguages` (`idLenguages`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iteandes_novatik`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iteandes_novatik`.`Student` (
  `idStudent` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `gradeYear` SMALLINT(4) NOT NULL,
  `modality` ENUM('Bachiler', 'Tecnico') NOT NULL,
  `Institution` VARCHAR(300) NOT NULL,
  `Person_idPerson` BIGINT UNSIGNED NOT NULL,
  `stateStudent` ENUM('Activo','Inactivo') NOT NULL,
  PRIMARY KEY (`idStudent`),
  INDEX `fk_Student_Person1_idx` (`Person_idPerson` ASC) ,
  CONSTRAINT `fk_Student_Person1`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `iteandes_novatik`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iteandes_novatik`.`TrainingProgram`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iteandes_novatik`.`TrainingProgram` (
  `idTrainingProgram` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codeTrainingProgram` BIGINT UNSIGNED NOT NULL,
  `nameTrainingProgram` VARCHAR(500) NOT NULL,
  `version` FLOAT NOT NULL,
  `statusTrainingProgram` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`idTrainingProgram`),
  UNIQUE INDEX `codeTrainingProgram_UNIQUE` (`codeTrainingProgram` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iteandes_novatik`.`TrainingCompetition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iteandes_novatik`.`TrainingCompetition` (
  `idTrainingCompetition` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codeTrainingCompetition` BIGINT NOT NULL,
  `denomination` VARCHAR(300) NOT NULL,
  `duration` TINYINT NOT NULL,
  `minimumSpace` TINYINT NOT NULL,
  `order` TINYINT NOT NULL,
  `statusTrainingCompetition` ENUM('Activo', 'Inactivo') NOT NULL,
  `TrainingProgram_idTrainingProgram` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idTrainingCompetition`),
  UNIQUE INDEX `codeTrainingCompetition_UNIQUE` (`codeTrainingCompetition` ASC) ,
  INDEX `fk_TrainingCompetition_TrainingProgram1_idx` (`TrainingProgram_idTrainingProgram` ASC) ,
  CONSTRAINT `fk_TrainingCompetition_TrainingProgram1`
    FOREIGN KEY (`TrainingProgram_idTrainingProgram`)
    REFERENCES `iteandes_novatik`.`TrainingProgram` (`idTrainingProgram`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iteandes_novatik`.`LearningResult`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iteandes_novatik`.`LearningResult` (
  `idLearningResult` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codeLearningResult` BIGINT NOT NULL,
  `nameLearningResult` VARCHAR(500) NOT NULL,
  `durationLearningResult` TINYINT NOT NULL,
  `statuLearningResult` ENUM('Activo', 'Inactivo') NOT NULL,
  `TrainingCompetition_idTrainingCompetition` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idLearningResult`),
  UNIQUE INDEX `codeLearningResult_UNIQUE` (`codeLearningResult` ASC) ,
  INDEX `fk_LearningResult_TrainingCompetition1_idx` (`TrainingCompetition_idTrainingCompetition` ASC) ,
  CONSTRAINT `fk_LearningResult_TrainingCompetition1`
    FOREIGN KEY (`TrainingCompetition_idTrainingCompetition`)
    REFERENCES `iteandes_novatik`.`TrainingCompetition` (`idTrainingCompetition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iteandes_novatik`.`Activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iteandes_novatik`.`Activity` (
  `idActivity` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codeActivity` BIGINT NOT NULL,
  `nameActivity` VARCHAR(300) NOT NULL,
  `descriptionActivity` VARCHAR(500) NOT NULL,
  `typeActivity` ENUM('Desempeño', 'Producto', 'Conocimiento') NOT NULL,
  `LearningResult_idLearningResult` BIGINT UNSIGNED NOT NULL,
  `stateActivity` ENUM('Activo','Inactivo') NOT NULL,
  PRIMARY KEY (`idActivity`),
  UNIQUE INDEX `codeActivity_UNIQUE` (`codeActivity` ASC) ,
  INDEX `fk_Activity_LearningResult1_idx` (`LearningResult_idLearningResult` ASC) ,
  CONSTRAINT `fk_Activity_LearningResult1`
    FOREIGN KEY (`LearningResult_idLearningResult`)
    REFERENCES `iteandes_novatik`.`LearningResult` (`idLearningResult`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iteandes_novatik`.`Note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iteandes_novatik`.`Note` (
  `idNote` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dateNote` DATE NOT NULL,
  `valueNote` FLOAT NOT NULL,
  `Activity_idActivity` BIGINT UNSIGNED NOT NULL,
  `Teacher_idTeacher` BIGINT UNSIGNED NOT NULL,
  `stateNote` ENUM('Activo','Inactivo') NOT NULL,
  PRIMARY KEY (`idNote`),
  INDEX `fk_Note_Activity1_idx` (`Activity_idActivity` ASC) ,
  INDEX `fk_Note_Teacher1_idx` (`Teacher_idTeacher` ASC) ,
  CONSTRAINT `fk_Note_Activity1`
    FOREIGN KEY (`Activity_idActivity`)
    REFERENCES `iteandes_novatik`.`Activity` (`idActivity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Note_Teacher1`
    FOREIGN KEY (`Teacher_idTeacher`)
    REFERENCES `iteandes_novatik`.`Teacher` (`idTeacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iteandes_novatik`.`Semester`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iteandes_novatik`.`Semester` (
  `idSemester` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nameSemester` VARCHAR(250) NOT NULL,
  `descriptionSemester` VARCHAR(500) NULL,
  `starDateSemester` DATE NOT NULL,
  `endDateSemester` DATE NOT NULL,
  `startDate50` DATE NOT NULL,
  `endDate50` DATE NOT NULL,
  `starDate2Semester` DATE NOT NULL,
  `endDate2Semester` DATE NOT NULL,
  `statuSemester` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`idSemester`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iteandes_novatik`.`Enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iteandes_novatik`.`Enrollment` (
  `idEnrollment` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dateEnrollment` DATE NOT NULL,
  `stateEnrollment` ENUM('Activo', 'Inactivo') NOT NULL,
  `Student_idStudent` BIGINT UNSIGNED NOT NULL,
  `Semester_idSemester` BIGINT UNSIGNED NOT NULL,
  `TrainingProgram_idTrainingProgram` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEnrollment`),
  INDEX `fk_Enrollment_Student1_idx` (`Student_idStudent` ASC) ,
  INDEX `fk_Enrollment_Semester1_idx` (`Semester_idSemester` ASC) ,
  INDEX `fk_Enrollment_TrainingProgram1_idx` (`TrainingProgram_idTrainingProgram` ASC) ,
  CONSTRAINT `fk_Enrollment_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `iteandes_novatik`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enrollment_Semester1`
    FOREIGN KEY (`Semester_idSemester`)
    REFERENCES `iteandes_novatik`.`Semester` (`idSemester`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enrollment_TrainingProgram1`
    FOREIGN KEY (`TrainingProgram_idTrainingProgram`)
    REFERENCES `iteandes_novatik`.`TrainingProgram` (`idTrainingProgram`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iteandes_novatik`.`Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iteandes_novatik`.`Group` (
  `idGroup` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codeGroup` BIGINT NOT NULL,
  `nameGroup` VARCHAR(300) NOT NULL,
  `minimumSpaceGroup` TINYINT NOT NULL,
  `maximumSpaceGroup` BIGINT NOT NULL,
  `stateGroup` ENUM('Activo', 'Inactivo') NOT NULL,
  `TrainingCompetition_idTrainingCompetition` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idGroup`),
  UNIQUE INDEX `codeGroup_UNIQUE` (`codeGroup` ASC) ,
  INDEX `fk_Group_TrainingCompetition1_idx` (`TrainingCompetition_idTrainingCompetition` ASC) ,
  CONSTRAINT `fk_Group_TrainingCompetition1`
    FOREIGN KEY (`TrainingCompetition_idTrainingCompetition`)
    REFERENCES `iteandes_novatik`.`TrainingCompetition` (`idTrainingCompetition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iteandes_novatik`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iteandes_novatik`.`Schedule` (
  `idSchedule` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `startDateSchedule` DATE NOT NULL,
  `endDateSchedule` DATE NOT NULL,
  `cantHours` TINYINT NOT NULL,
  `startHourSchedule` TIME NOT NULL,
  `endHourSchedule` TIME NOT NULL,
  `stateSchedule` ENUM('Activo', 'Inactivo') NOT NULL,
  `Group_idGroup` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idSchedule`),
  INDEX `fk_Schedule_Group1_idx` (`Group_idGroup` ASC) ,
  CONSTRAINT `fk_Schedule_Group1`
    FOREIGN KEY (`Group_idGroup`)
    REFERENCES `iteandes_novatik`.`Group` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iteandes_novatik`.`EnrollmentCompetition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iteandes_novatik`.`EnrollmentCompetition` (
  `idEnrollmentCompetition` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Enrollment_idEnrollment` BIGINT UNSIGNED NOT NULL,
  `Schedule_idSchedule` BIGINT UNSIGNED NOT NULL,
  `TrainingCompetition_idTrainingCompetition` BIGINT UNSIGNED NOT NULL,
  `stateEnrollmentCompetition` ENUM('Activo','Inactivo') NOT NULL,
  PRIMARY KEY (`idEnrollmentCompetition`),
  INDEX `fk_EnrollmentCompetition_Enrollment1_idx` (`Enrollment_idEnrollment` ASC) ,
  INDEX `fk_EnrollmentCompetition_Schedule1_idx` (`Schedule_idSchedule` ASC) ,
  INDEX `fk_EnrollmentCompetition_TrainingCompetition1_idx` (`TrainingCompetition_idTrainingCompetition` ASC) ,
  CONSTRAINT `fk_EnrollmentCompetition_Enrollment1`
    FOREIGN KEY (`Enrollment_idEnrollment`)
    REFERENCES `iteandes_novatik`.`Enrollment` (`idEnrollment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EnrollmentCompetition_Schedule1`
    FOREIGN KEY (`Schedule_idSchedule`)
    REFERENCES `iteandes_novatik`.`Schedule` (`idSchedule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EnrollmentCompetition_TrainingCompetition1`
    FOREIGN KEY (`TrainingCompetition_idTrainingCompetition`)
    REFERENCES `iteandes_novatik`.`TrainingCompetition` (`idTrainingCompetition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iteandes_novatik`.`Archive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iteandes_novatik`.`Archive` (
  `idArchive` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nameArchive` VARCHAR(300) NOT NULL,
  `descriptionArchive` VARCHAR(250) NOT NULL,
  `stateArchive` ENUM('Activo', 'Inactivo') NOT NULL,
  `rutaArchive` VARCHAR(500) NOT NULL,
  `Activity_idActivity` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idArchive`),
  INDEX `fk_Archive_Activity1_idx` (`Activity_idActivity` ASC) ,
  CONSTRAINT `fk_Archive_Activity1`
    FOREIGN KEY (`Activity_idActivity`)
    REFERENCES `iteandes_novatik`.`Activity` (`idActivity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
